---
scripts:
  - assets/main.js
styles:
  - assets/main.css
project: (Replace)
structure:
  - Introduction
  - - ./welcome.md
  - Atoms
  - - ./button/button.md
    - - ./button/button.md
    - ./welcome.md
...