---
project: Test Project
scripts:
  - assets/main.js
styles:
  - assets/main.css
structure:
  - Introduction
  - - ./welcome.md
  - Atoms
  - - ./button/button.md
    - - ./button/button.md
    - ./welcome.md
twigFilters:
  t: (text) => `${text} (translated)`
...